PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> orange
      [3] --> yellow
      [4] --> green
      [5] --> blue
      [6] --> purple
      [7] --> brown
      [8] --> black
ObjectDeclaration
  names ===
    [0] --> sky
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> color
    constraint: (null)
  initializer: (null)
AssignStmt
  labels === (null/empty)
  name: SimpleName
    id --> sky
  expr: NameExpr
    name: SimpleName
      id --> blue


Listing for tst/statements/tst00006.ada:
==========================================
     1   type color is (white, red, orange, yellow, green, blue, purple, brown, black);
     2   sky : color;
     3   sky := blue;
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: color
EnumLiteral Symbol: white of type color
EnumLiteral Symbol: red of type color
EnumLiteral Symbol: orange of type color
EnumLiteral Symbol: yellow of type color
EnumLiteral Symbol: green of type color
EnumLiteral Symbol: blue of type color
EnumLiteral Symbol: purple of type color
EnumLiteral Symbol: brown of type color
EnumLiteral Symbol: black of type color
Object Symbol: sky
-------------------

   Errors  : 0
   Warnings: 0
