PRINTING THE AST STRUCTURE
==========================
ObjectDeclaration
  names ===
    [0] --> x
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)
  initializer: IntLiteralExpr
    value --> 25
LoopStmt
  labels === (null/empty)
  name: (null)
  kind --> While
  expr: BinaryExpr
    op --> > (greater)
    lhs: NameExpr
      name: SimpleName
        id --> x
    rhs: IntLiteralExpr
      value --> 0
  stmts ===
    [0]: AssignStmt
      labels === (null/empty)
      name: SimpleName
        id --> x
      expr: BinaryExpr
        op --> - (minus)
        lhs: NameExpr
          name: SimpleName
            id --> x
        rhs: IntLiteralExpr
          value --> 1


Listing for tst/statements/tst00011.ada:
==========================================
     1   X : INTEGER := 25;
     2
     3   while x > 0 loop
     4      X := X - 1;
     5   end loop;
     6


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: x
-------------------

   Errors  : 0
   Warnings: 0
