PRINTING THE AST STRUCTURE
==========================
ObjectDeclaration
  names ===
    [0] --> x
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)
  initializer: IntLiteralExpr
    value --> 0
LoopStmt
  labels === (null/empty)
  name: (null)
  kind --> None
  expr: (null)
  stmts ===
    [0]: AssignStmt
      labels === (null/empty)
      name: SimpleName
        id --> x
      expr: BinaryExpr
        op --> + (plus)
        lhs: NameExpr
          name: SimpleName
            id --> x
        rhs: IntLiteralExpr
          value --> 1
    [1]: ExitStmt
      labels === (null/empty)
      name: (null)
      when: BinaryExpr
        op --> = (equal)
        lhs: NameExpr
          name: SimpleName
            id --> x
        rhs: IntLiteralExpr
          value --> 25


Listing for tst/statements/tst00010.ada:
==========================================
     1   X : INTEGER := 0;
     2
     3   loop
     4      X := X + 1;
     5      exit when x = 25;
     6   end loop;


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: x : Object
-------------------

   Errors  : 0
   Warnings: 0
