PRINTING THE AST STRUCTURE
==========================
NullStatement
  labels === (null/empty)


Listing for tst/statements/tst00001.ada:
==========================================
     1   null;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
-------------------

   Errors  : 0
   Warnings: 0
