PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: (null)
TypeDecl
  name --> person_name
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> person
      constraint: (null)
TypeDecl
  name --> month_name
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> jan
      [1] --> feb
      [2] --> mar
      [3] --> apr
      [4] --> may
      [5] --> jun
      [6] --> jul
      [7] --> aug
      [8] --> sep
      [9] --> oct
      [10] --> nov
      [11] --> dec
TypeDecl
  name --> date
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> day
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 1
                upper: IntLiteralExpr
                  value --> 31
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> month
          type: SubtypeIndication
            type_mark: SimpleName
              id --> month_name
            constraint: (null)
          initializer: (null)
        [2]: ComponentDeclaration
          names ===
            [0] --> year
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 0
                upper: IntLiteralExpr
                  value --> 4000
          initializer: (null)
      variant part: (null)
ObjectDeclaration
  names ===
    [0] --> tomorrow
    [1] --> yesterday
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> date
    constraint: (null)
  initializer: (null)
TypeDecl
  name --> car
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> number
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: (null)
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> owner
          type: SubtypeIndication
            type_mark: SimpleName
              id --> person_name
            constraint: (null)
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> car_name
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> car
      constraint: (null)
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> name
          type: SubtypeIndication
            type_mark: SimpleName
              id --> string
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: IntLiteralExpr
                    value --> 20
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> birth
          type: SubtypeIndication
            type_mark: SimpleName
              id --> date
            constraint: (null)
          initializer: (null)
        [2]: ComponentDeclaration
          names ===
            [0] --> age
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 0
                upper: IntLiteralExpr
                  value --> 130
          initializer: (null)
        [3]: ComponentDeclaration
          names ===
            [0] --> vehicle
          type: SubtypeIndication
            type_mark: SimpleName
              id --> car_name
            constraint: (null)
          initializer: (null)
      variant part: VariantPart
        name: SimpleName
          id --> sex
        variants ===
          [0]: Variant
            choices ===
              [0]: ExprChoice
                expr: NameExpr
                  name: SimpleName
                    id --> m
            components: ComponentList
              components ===
                [0]: ComponentDeclaration
                  names ===
                    [0] --> wife
                  type: SubtypeIndication
                    type_mark: SimpleName
                      id --> person_name
                    constraint: DiscriminantConstraint
                      list ===
                        [0]: DiscriminantAssociation
                          name ===
                            [0]: SimpleName
                              id --> sex
                          expr: NameExpr
                            name: SimpleName
                              id --> f
                  initializer: (null)
              variant part: (null)
          [1]: Variant
            choices ===
              [0]: ExprChoice
                expr: NameExpr
                  name: SimpleName
                    id --> f
            components: ComponentList
              components ===
                [0]: ComponentDeclaration
                  names ===
                    [0] --> husband
                  type: SubtypeIndication
                    type_mark: SimpleName
                      id --> person_name
                    constraint: DiscriminantConstraint
                      list ===
                        [0]: DiscriminantAssociation
                          name ===
                            [0]: SimpleName
                              id --> sex
                          expr: NameExpr
                            name: SimpleName
                              id --> m
                  initializer: (null)
              variant part: (null)


Listing for tst/declarations/tst00102.ada:
==========================================
     1   type GENDER is (M, F);
     2
     3   type PERSON(SEX : GENDER);
     4
     5   type PERSON_NAME is access PERSON;
     6
     7   type MONTH_NAME is (JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC);
     8
     9   type DATE is
    10       record
    11           DAY : INTEGER range 1 .. 31;
    12           MONTH : MONTH_NAME;
    13           YEAR : INTEGER range 0 .. 4000;
    14       end record;
    15   TOMORROW, YESTERDAY : DATE;
    16
    17   type CAR is
    18       record
    19           NUMBER : INTEGER;
    20           OWNER : PERSON_NAME;
    21       end record;
    22
    23   type CAR_NAME is access CAR;
    24
    25   type PERSON(SEX : GENDER) is
    26       record
    27           NAME : STRING(1 .. 20);
    28           BIRTH : DATE;
    29           AGE : INTEGER range 0 .. 130;
    30           VEHICLE : CAR_NAME;
    31           case sex is
    32               when M => WIFE : PERSON_NAME(SEX => F);
    33               when F => HUSBAND : PERSON_NAME(SEX => M);
    34           end case;
    35       end record;
    36


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: gender
EnumLiteral Symbol: m of type gender
EnumLiteral Symbol: f of type gender
Type Symbol: person
Discriminant Symbol: sex of type gender
Type Symbol: person_name
Type Symbol: month_name
EnumLiteral Symbol: jan of type month_name
EnumLiteral Symbol: feb of type month_name
EnumLiteral Symbol: mar of type month_name
EnumLiteral Symbol: apr of type month_name
EnumLiteral Symbol: may of type month_name
EnumLiteral Symbol: jun of type month_name
EnumLiteral Symbol: jul of type month_name
EnumLiteral Symbol: aug of type month_name
EnumLiteral Symbol: sep of type month_name
EnumLiteral Symbol: oct of type month_name
EnumLiteral Symbol: nov of type month_name
EnumLiteral Symbol: dec of type month_name
Type Symbol: date
Component Symbol: day of type date
Component Symbol: month of type date
Component Symbol: year of type date
Object Symbol: tomorrow
Object Symbol: yesterday
Type Symbol: car
Component Symbol: number of type car
Component Symbol: owner of type car
Type Symbol: car_name
Discriminant Symbol: sex of type gender
Component Symbol: name of type person
Component Symbol: birth of type person
Component Symbol: age of type person
Component Symbol: vehicle of type person
Component Symbol: wife of type person
Component Symbol: husband of type person
-------------------

   Errors  : 0
   Warnings: 0
