ObjectDeclaration
  names ===
    [0] --> max_line_size
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 132
TypeDecl
  name --> line
  discriminantPart === (null)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: NameExpr
            name: SimpleName
              id --> max_line_size
    component: SubtypeIndication
      type_mark: SimpleName
        id --> character
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> page
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 50
    component: SubtypeIndication
      type_mark: SimpleName
        id --> line
      constraint: (null)
  initializer: (null)


Listing for tst/declarations/tst00063.ada:
==========================================
     1   MAX_LINE_SIZE : constant := 132;
     2   type LINE is array(1 .. MAX_LINE_SIZE) of CHARACTER;
     3   PAGE : array(1 .. 50) of LINE;
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: max_line_size : Object
Array Type: line : Array
Object Symbol: page : Object
-------------------
