PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> roman_digit
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'I'
      [1] --> 'V'
      [2] --> 'X'
      [3] --> 'L'
      [4] --> 'C'
      [5] --> 'D'
      [6] --> 'M'


Listing for tst/declarations/tst00039.ada:
==========================================
     1   type ROMAN_DIGIT is ('I', 'V', 'X', 'L', 'C', 'D', 'M');
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: roman_digit
EnumLiteral Symbol: 'I' of type roman_digit
EnumLiteral Symbol: 'V' of type roman_digit
EnumLiteral Symbol: 'X' of type roman_digit
EnumLiteral Symbol: 'L' of type roman_digit
EnumLiteral Symbol: 'C' of type roman_digit
EnumLiteral Symbol: 'D' of type roman_digit
EnumLiteral Symbol: 'M' of type roman_digit
-------------------

   Errors  : 0
   Warnings: 0
