PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> level
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> low
      [1] --> medium
      [2] --> urgent


Listing for tst/declarations/tst00031.ada:
==========================================
     1   type LEVEL is (LOW, MEDIUM, URGENT);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: level : Type
EnumLiteral Symbol: low : EnumLiteral of type level
EnumLiteral Symbol: medium : EnumLiteral of type level
EnumLiteral Symbol: urgent : EnumLiteral of type level
-------------------

   Errors  : 0
   Warnings: 0
