PRINTING THE AST STRUCTURE
==========================
ObjectDeclaration
  names ===
    [0] --> n
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 10
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> yellow
      [3] --> green
      [4] --> blue
      [5] --> brown
      [6] --> black
ObjectDeclaration
  names ===
    [0] --> color_table
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: NameExpr
            name: SimpleName
              id --> n
    component: SubtypeIndication
      type_mark: SimpleName
        id --> color
      constraint: (null)
  initializer: (null)


Listing for tst/declarations/tst00004.ada:
==========================================
     1   N : constant := 10;
     2   type COLOR is (WHITE, RED, YELLOW, GREEN, BLUE, BROWN, BLACK);
     3   COLOR_TABLE : ARRAY(1 .. N) of COLOR;
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: n
Type Symbol: color
EnumLiteral Symbol: white of type color
EnumLiteral Symbol: red of type color
EnumLiteral Symbol: yellow of type color
EnumLiteral Symbol: green of type color
EnumLiteral Symbol: blue of type color
EnumLiteral Symbol: brown of type color
EnumLiteral Symbol: black of type color
Object Symbol: color_table
-------------------

   Errors  : 0
   Warnings: 0
