TypeDecl
  name --> mixed
  discriminantPart === (null)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'A'
      [1] --> 'B'
      [2] --> '*'
      [3] --> b
      [4] --> none
      [5] --> '?'
      [6] --> '%'


Listing for tst/declarations/tst00035.ada:
==========================================
     1   type MIXED is ('A', 'B', '*', B, NONE, '?', '%');
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Enumeration Type: mixed : Enumeration
   containing literals ('A' 'B' '*' b none '?' '%' )
Enumeration Literal: 'A' : EnumLiteral of type mixed; value (0)
Enumeration Literal: 'B' : EnumLiteral of type mixed; value (1)
Enumeration Literal: '*' : EnumLiteral of type mixed; value (2)
Enumeration Literal: b : EnumLiteral of type mixed; value (3)
Enumeration Literal: none : EnumLiteral of type mixed; value (4)
Enumeration Literal: '?' : EnumLiteral of type mixed; value (5)
Enumeration Literal: '%' : EnumLiteral of type mixed; value (6)
-------------------
