PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> key_manager
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)


Listing for tst/declarations/tst00027.ada:
==========================================
     1   subtype KEY_MANAGER is INTEGER;
     2
     3   --type SPECIAL_KEY is new KEY_MANAGER.KEY;
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Subtype: key_manager : Subtype
-------------------

   Errors  : 0
   Warnings: 0
