PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> cell
  discriminantPart === (null/empty)
  definition: (null)


Listing for tst/declarations/tst00092.ada:
==========================================
     1   type CELL;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
IncompleteType Symbol: cell
-------------------

   Errors  : 0
   Warnings: 0
