PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> hexa
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'A'
      [1] --> 'B'
      [2] --> 'C'
      [3] --> 'D'
      [4] --> 'E'
      [5] --> 'F'


Listing for tst/declarations/tst00034.ada:
==========================================
     1   type HEXA is ('A', 'B', 'C', 'D', 'E', 'F');
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: hexa
EnumLiteral Symbol: 'A' of type hexa
EnumLiteral Symbol: 'B' of type hexa
EnumLiteral Symbol: 'C' of type hexa
EnumLiteral Symbol: 'D' of type hexa
EnumLiteral Symbol: 'E' of type hexa
EnumLiteral Symbol: 'F' of type hexa
-------------------

   Errors  : 0
   Warnings: 0
