TypeDecl
  name --> matrix
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
        [1]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> real
      constraint: (null)
TypeDecl
  name --> square
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> side
      type: SimpleName
        id --> integer
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> mat
          type: SubtypeIndication
            type_mark: SimpleName
              id --> matrix
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> side
                [1]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> side
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> double_square
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> number
      type: SimpleName
        id --> integer
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> left
          type: SubtypeIndication
            type_mark: SimpleName
              id --> square
            constraint: DiscriminantConstraint
              list ===
                [0]: DiscriminantAssociation
                  name === (null/empty)
                  expr: NameExpr
                    name: SimpleName
                      id --> number
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> right
          type: SubtypeIndication
            type_mark: SimpleName
              id --> square
            constraint: DiscriminantConstraint
              list ===
                [0]: DiscriminantAssociation
                  name === (null/empty)
                  expr: NameExpr
                    name: SimpleName
                      id --> number
          initializer: (null)
      variant part: (null)


Listing for tst/declarations/tst00080.ada:
==========================================
     1   type MATRIX is array(INTEGER range <>, INTEGER range <>) of REAL;
     2
     3   type SQUARE(SIDE : INTEGER) is
     4       record
     5           MAT : MATRIX(1 .. SIDE, 1 .. SIDE);
     6       end record;
     7
     8   type DOUBLE_SQUARE(NUMBER : INTEGER) is
     9       record
    10           LEFT : SQUARE(NUMBER);
    11           RIGHT : SQUARE(NUMBER);
    12       end record;
    13


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Array Type: matrix : Array
Discriminant Symbol: side : Discriminant
Record Type: square : Record
   containing components (mat )
Discriminant Symbol: number : Discriminant
Record Type: double_square : Record
   containing components (left right )
-------------------

Scope Name: square
Scope ID  : 2
-------------------
Component Symbol: mat : Component
-------------------

Scope Name: double_square
Scope ID  : 3
-------------------
Component Symbol: left : Component
Component Symbol: right : Component
-------------------
