PRINTING THE AST STRUCTURE
==========================


Listing for tst/declarations/tst00008.ada:
==========================================
     1   -- TOLLERANCE : constant REAL := DISPERSION(1.15):
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
-------------------

   Errors  : 0
   Warnings: 0
