PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: (null)
TypeDecl
  name --> male
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> person
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name ===
            [0]: SimpleName
              id --> sex
          expr: NameExpr
            name: SimpleName
              id --> m


Listing for tst/declarations/tst00023.ada:
==========================================
     1   type GENDER is (M, F);
     2   type PERSON(SEX : GENDER);
     3   subtype MALE is PERSON(SEX => M);
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: gender
EnumLiteral Symbol: m of type gender
EnumLiteral Symbol: f of type gender
IncompleteType Symbol: person
Discriminant Symbol: sex of type person
Type Symbol: male
-------------------

   Errors  : 0
   Warnings: 0
