PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> bit_vector
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> count
    [1] --> sum
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)
  initializer: (null)
ObjectDeclaration
  names ===
    [0] --> size
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 0
        upper: IntLiteralExpr
          value --> 10_000
  initializer: IntLiteralExpr
    value --> 0
ObjectDeclaration
  names ===
    [0] --> sorted
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> boolean
    constraint: (null)
  initializer: NameExpr
    name: SimpleName
      id --> false
ObjectDeclaration
  names ===
    [0] --> n
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 3
ObjectDeclaration
  names ===
    [0] --> k
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 100
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> orange
      [3] --> yellow
      [4] --> green
      [5] --> blue
      [6] --> purple
      [7] --> brown
      [8] --> black
ObjectDeclaration
  names ===
    [0] --> color_table
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: NameExpr
            name: SimpleName
              id --> n
    component: SubtypeIndication
      type_mark: SimpleName
        id --> color
      constraint: (null)
  initializer: (null)
ObjectDeclaration
  names ===
    [0] --> limit
  constant --> true
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)
  initializer: IntLiteralExpr
    value --> 10_000
ObjectDeclaration
  names ===
    [0] --> low_limit
  constant --> true
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)
  initializer: BinaryExpr
    op --> / (divide)
    lhs: NameExpr
      name: SimpleName
        id --> limit
    rhs: IntLiteralExpr
      value --> 10
ObjectDeclaration
  names ===
    [0] --> pi
  constant --> true
  typeSpec: (null)
  initializer: RealLiteralExpr
    value --> 3.14159_26536
ObjectDeclaration
  names ===
    [0] --> two_pi
  constant --> true
  typeSpec: (null)
  initializer: BinaryExpr
    op --> * (times)
    lhs: IntLiteralExpr
      value --> 2
    rhs: NameExpr
      name: SimpleName
        id --> pi
ObjectDeclaration
  names ===
    [0] --> max
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 500
ObjectDeclaration
  names ===
    [0] --> power_16
  constant --> true
  typeSpec: (null)
  initializer: BinaryExpr
    op --> ** (power)
    lhs: IntLiteralExpr
      value --> 2
    rhs: IntLiteralExpr
      value --> 16
ObjectDeclaration
  names ===
    [0] --> one
    [1] --> un
    [2] --> eins
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 1
TypeDecl
  name --> column
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Integer
    size: (null)
    range: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: IntLiteralExpr
          value --> 72
TypeDecl
  name --> table
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 10
    component: SubtypeIndication
      type_mark: SimpleName
        id --> integer
      constraint: (null)
TypeDecl
  name --> matrix
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
        [1]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> real
      constraint: (null)
TypeDecl
  name --> rainbow
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> color
    constraint: RangeConstraint
      range: Range
        lower: NameExpr
          name: SimpleName
            id --> red
        upper: NameExpr
          name: SimpleName
            id --> purple
TypeDecl
  name --> red_purple
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> rainbow
    constraint: (null)
TypeDecl
  name --> int
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)
TypeDecl
  name --> small_int
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: RangeConstraint
      range: Range
        lower: UnaryExpr
          op --> - (minus)
          operand: IntLiteralExpr
            value --> 10
        upper: IntLiteralExpr
          value --> 10
TypeDecl
  name --> up_to_k
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> column
    constraint: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: NameExpr
          name: SimpleName
            id --> k
TypeDecl
  name --> square_sub
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> matrix
    constraint: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 10
        [1]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 10
TypeDecl
  name --> coordinate
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> lat
          type: SubtypeIndication
            type_mark: SimpleName
              id --> real
            constraint: (null)
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> long
          type: SubtypeIndication
            type_mark: SimpleName
              id --> real
            constraint: (null)
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> local_coordinate
  discriminantPart === (null/empty)
  definition: DerivedTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> coordinate
      constraint: (null)
TypeDecl
  name --> day
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> mon
      [1] --> tue
      [2] --> wed
      [3] --> thu
      [4] --> fri
      [5] --> sat
      [6] --> sun
TypeDecl
  name --> midweek
  discriminantPart === (null/empty)
  definition: DerivedTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> day
      constraint: RangeConstraint
        range: Range
          lower: NameExpr
            name: SimpleName
              id --> tue
          upper: NameExpr
            name: SimpleName
              id --> thu
TypeDecl
  name --> positive
  discriminantPart === (null/empty)
  definition: DerivedTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> integer
      constraint: (null)
TypeDecl
  name --> counter
  discriminantPart === (null/empty)
  definition: DerivedTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> positive
      constraint: (null)
TypeDecl
  name --> suit
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> clubs
      [1] --> diamonds
      [2] --> hearts
      [3] --> spades
TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f
TypeDecl
  name --> level
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> low
      [1] --> medium
      [2] --> urgent
TypeDecl
  name --> light
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> red
      [1] --> amber
      [2] --> green
TypeDecl
  name --> hexa
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'A'
      [1] --> 'B'
      [2] --> 'C'
      [3] --> 'D'
      [4] --> 'E'
      [5] --> 'F'
TypeDecl
  name --> mixed
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'A'
      [1] --> 'B'
      [2] --> '*'
      [3] --> none
      [4] --> '?'
      [5] --> '%'
TypeDecl
  name --> weekday
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> day
    constraint: RangeConstraint
      range: Range
        lower: NameExpr
          name: SimpleName
            id --> mon
        upper: NameExpr
          name: SimpleName
            id --> fri
TypeDecl
  name --> major
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> suit
    constraint: RangeConstraint
      range: Range
        lower: NameExpr
          name: SimpleName
            id --> hearts
        upper: NameExpr
          name: SimpleName
            id --> spades
TypeDecl
  name --> roman_digit
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'I'
      [1] --> 'V'
      [2] --> 'X'
      [3] --> 'L'
      [4] --> 'C'
      [5] --> 'D'
      [6] --> 'M'
TypeDecl
  name --> page_num
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Integer
    size: (null)
    range: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: IntLiteralExpr
          value --> 2_000
ObjectDeclaration
  names ===
    [0] --> max_line_size
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 132
TypeDecl
  name --> line_size
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Integer
    size: (null)
    range: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: NameExpr
          name: SimpleName
            id --> max_line_size
TypeDecl
  name --> column_ptr
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> line_size
    constraint: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: IntLiteralExpr
          value --> 10
TypeDecl
  name --> buffer_size
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 0
        upper: NameExpr
          name: SimpleName
            id --> max
TypeDecl
  name --> coefficient
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Floating Point
    digits: IntLiteralExpr
      value --> 4
    range: RangeConstraint
      range: Range
        lower: UnaryExpr
          op --> - (minus)
          operand: RealLiteralExpr
            value --> 1.0
        upper: RealLiteralExpr
          value --> 1.0
TypeDecl
  name --> mass
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Floating Point
    digits: IntLiteralExpr
      value --> 7
    range: RangeConstraint
      range: Range
        lower: RealLiteralExpr
          value --> 0.0
        upper: RealLiteralExpr
          value --> 1.0E35
TypeDecl
  name --> short_coeff
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> coefficient
    constraint: RealConstraint
      range: NumericTypeSpec
        kind --> Floating Point
        digits: IntLiteralExpr
          value --> 5
        range: (null)
TypeDecl
  name --> probability
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> real
    constraint: RangeConstraint
      range: Range
        lower: RealLiteralExpr
          value --> 0.0
        upper: RealLiteralExpr
          value --> 1.0
TypeDecl
  name --> volt
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Fixed Point
    delta: RealLiteralExpr
      value --> 0.125
    range: RangeConstraint
      range: Range
        lower: RealLiteralExpr
          value --> 0.0
        upper: RealLiteralExpr
          value --> 255.0
TypeDecl
  name --> rough_voltage
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> volt
    constraint: RealConstraint
      range: NumericTypeSpec
        kind --> Fixed Point
        delta: RealLiteralExpr
          value --> 1.0
        range: (null)
ObjectDeclaration
  names ===
    [0] --> word_length
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 8
ObjectDeclaration
  names ===
    [0] --> del
  constant --> true
  typeSpec: (null)
  initializer: BinaryExpr
    op --> / (divide)
    lhs: RealLiteralExpr
      value --> 1.0
    rhs: BinaryExpr
      op --> ** (power)
      lhs: IntLiteralExpr
        value --> 2
      rhs: BinaryExpr
        op --> - (minus)
        lhs: NameExpr
          name: SimpleName
            id --> word_length
        rhs: IntLiteralExpr
          value --> 1
TypeDecl
  name --> fraction
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Fixed Point
    delta: NameExpr
      name: SimpleName
        id --> del
    range: RangeConstraint
      range: Range
        lower: UnaryExpr
          op --> - (minus)
          operand: RealLiteralExpr
            value --> 1.0
        upper: BinaryExpr
          op --> - (minus)
          lhs: RealLiteralExpr
            value --> 1.0
          rhs: NameExpr
            name: SimpleName
              id --> del
TypeDecl
  name --> vector
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> real
      constraint: (null)
TypeDecl
  name --> roman
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> positive
    component: SubtypeIndication
      type_mark: SimpleName
        id --> roman_digit
      constraint: (null)
TypeDecl
  name --> schedule
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: SubtypeRange
          subtype: SubtypeIndication
            type_mark: SimpleName
              id --> day
            constraint: (null)
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
TypeDecl
  name --> line
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: NameExpr
            name: SimpleName
              id --> max_line_size
    component: SubtypeIndication
      type_mark: SimpleName
        id --> character
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> grid
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 80
        [1]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 100
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
  initializer: (null)
ObjectDeclaration
  names ===
    [0] --> mix
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: SubtypeRange
          subtype: SubtypeIndication
            type_mark: SimpleName
              id --> color
            constraint: RangeConstraint
              range: Range
                lower: NameExpr
                  name: SimpleName
                    id --> red
                upper: NameExpr
                  name: SimpleName
                    id --> green
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
  initializer: (null)
ObjectDeclaration
  names ===
    [0] --> page
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 50
    component: SubtypeIndication
      type_mark: SimpleName
        id --> line
      constraint: (null)
  initializer: (null)
TypeDecl
  name --> month_name
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> jan
      [1] --> feb
      [2] --> mar
      [3] --> apr
      [4] --> may
      [5] --> jun
      [6] --> jul
      [7] --> aug
      [8] --> sep
      [9] --> oct
      [10] --> nov
      [11] --> dec
TypeDecl
  name --> date
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> day
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 1
                upper: IntLiteralExpr
                  value --> 31
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> month
          type: SubtypeIndication
            type_mark: SimpleName
              id --> month_name
            constraint: (null)
          initializer: (null)
        [2]: ComponentDeclaration
          names ===
            [0] --> year
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 0
                upper: IntLiteralExpr
                  value --> 4000
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> complex
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> re
          type: SubtypeIndication
            type_mark: SimpleName
              id --> real
            constraint: (null)
          initializer: RealLiteralExpr
            value --> 0.0
        [1]: ComponentDeclaration
          names ===
            [0] --> im
          type: SubtypeIndication
            type_mark: SimpleName
              id --> real
            constraint: (null)
          initializer: RealLiteralExpr
            value --> 0.0
      variant part: (null)
ObjectDeclaration
  names ===
    [0] --> tomorrow
    [1] --> yesterday
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> date
    constraint: (null)
  initializer: (null)
ObjectDeclaration
  names ===
    [0] --> a
    [1] --> b
    [2] --> c
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> complex
    constraint: (null)
  initializer: (null)
TypeDecl
  name --> buffer
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> size
      type: SimpleName
        id --> buffer_size
      expr: IntLiteralExpr
        value --> 100
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> pos
          type: SubtypeIndication
            type_mark: SimpleName
              id --> buffer_size
            constraint: (null)
          initializer: IntLiteralExpr
            value --> 0
        [1]: ComponentDeclaration
          names ===
            [0] --> value
          type: SubtypeIndication
            type_mark: SimpleName
              id --> string
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> size
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> square
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> side
      type: SimpleName
        id --> integer
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> mat
          type: SubtypeIndication
            type_mark: SimpleName
              id --> matrix
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> side
                [1]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> side
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> double_square
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> number
      type: SimpleName
        id --> integer
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> left
          type: SubtypeIndication
            type_mark: SimpleName
              id --> square
            constraint: DiscriminantConstraint
              list ===
                [0]: DiscriminantAssociation
                  name === (null/empty)
                  expr: NameExpr
                    name: SimpleName
                      id --> number
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> right
          type: SubtypeIndication
            type_mark: SimpleName
              id --> square
            constraint: DiscriminantConstraint
              list ===
                [0]: DiscriminantAssociation
                  name === (null/empty)
                  expr: NameExpr
                    name: SimpleName
                      id --> number
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> item
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> number
      type: SimpleName
        id --> positive
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> content
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: (null)
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> device
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> printer
      [1] --> disk
      [2] --> drum
TypeDecl
  name --> state
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> open
      [1] --> closed
TypeDecl
  name --> cylinder_index
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Integer
    size: (null)
    range: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: IntLiteralExpr
          value --> 50
TypeDecl
  name --> track_number
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Integer
    size: (null)
    range: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: IntLiteralExpr
          value --> 120
ObjectDeclaration
  names ===
    [0] --> page_size
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 55
TypeDecl
  name --> peripheral
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> unit
      type: SimpleName
        id --> device
      expr: NameExpr
        name: SimpleName
          id --> disk
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> status
          type: SubtypeIndication
            type_mark: SimpleName
              id --> state
            constraint: (null)
          initializer: (null)
      variant part: VariantPart
        name: SimpleName
          id --> unit
        variants ===
          [0]: Variant
            choices ===
              [0]: ExprChoice
                expr: NameExpr
                  name: SimpleName
                    id --> printer
            components: ComponentList
              components ===
                [0]: ComponentDeclaration
                  names ===
                    [0] --> line_count
                  type: SubtypeIndication
                    type_mark: SimpleName
                      id --> integer
                    constraint: RangeConstraint
                      range: Range
                        lower: IntLiteralExpr
                          value --> 1
                        upper: NameExpr
                          name: SimpleName
                            id --> page_size
                  initializer: (null)
              variant part: (null)
          [1]: Variant
            choices ===
              [0]: OthersChoice
                others --> Others
            components: ComponentList
              components ===
                [0]: ComponentDeclaration
                  names ===
                    [0] --> cylinder
                  type: SubtypeIndication
                    type_mark: SimpleName
                      id --> cylinder_index
                    constraint: (null)
                  initializer: (null)
                [1]: ComponentDeclaration
                  names ===
                    [0] --> track
                  type: SubtypeIndication
                    type_mark: SimpleName
                      id --> track_number
                    constraint: (null)
                  initializer: (null)
              variant part: (null)
TypeDecl
  name --> drum_unit
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> peripheral
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name === (null/empty)
          expr: NameExpr
            name: SimpleName
              id --> drum
TypeDecl
  name --> disk_unit
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> peripheral
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name === (null/empty)
          expr: NameExpr
            name: SimpleName
              id --> disk
ObjectDeclaration
  names ===
    [0] --> writer
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> peripheral
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name ===
            [0]: SimpleName
              id --> unit
          expr: NameExpr
            name: SimpleName
              id --> printer
  initializer: (null)
ObjectDeclaration
  names ===
    [0] --> archive
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> disk_unit
    constraint: (null)
  initializer: (null)
TypeDecl
  name --> frame
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> matrix
      constraint: (null)
TypeDecl
  name --> buffer_name
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> buffer
      constraint: (null)
TypeDecl
  name --> cell
  discriminantPart === (null/empty)
  definition: (null)
TypeDecl
  name --> link
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> cell
      constraint: (null)
TypeDecl
  name --> cell
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> value
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: (null)
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> succ
          type: SubtypeIndication
            type_mark: SimpleName
              id --> link
            constraint: (null)
          initializer: (null)
        [2]: ComponentDeclaration
          names ===
            [0] --> pred
          type: SubtypeIndication
            type_mark: SimpleName
              id --> link
            constraint: (null)
          initializer: (null)
      variant part: (null)
ObjectDeclaration
  names ===
    [0] --> head
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> link
    constraint: (null)
  initializer: SubtypeIndicationAllocatorExpr
    subtype: SubtypeIndication
      type_mark: SimpleName
        id --> cell
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> next
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> link
    constraint: (null)
  initializer: NameExpr
    name: SelectedName
      prefix: SimpleName
        id --> head
      selector: SimpleName
        id --> succ
      all --> false
TypeDecl
  name --> car
  discriminantPart === (null/empty)
  definition: (null)
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: (null)
TypeDecl
  name --> person_name
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> person
      constraint: (null)
TypeDecl
  name --> car_name
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> car
      constraint: (null)
TypeDecl
  name --> car
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> number
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: (null)
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> owner
          type: SubtypeIndication
            type_mark: SimpleName
              id --> person_name
            constraint: (null)
          initializer: (null)
      variant part: (null)
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> name
          type: SubtypeIndication
            type_mark: SimpleName
              id --> string
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: IntLiteralExpr
                    value --> 20
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> birth
          type: SubtypeIndication
            type_mark: SimpleName
              id --> date
            constraint: (null)
          initializer: (null)
        [2]: ComponentDeclaration
          names ===
            [0] --> age
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 1
                upper: IntLiteralExpr
                  value --> 130
          initializer: (null)
        [3]: ComponentDeclaration
          names ===
            [0] --> vehicle
          type: SubtypeIndication
            type_mark: SimpleName
              id --> car_name
            constraint: (null)
          initializer: (null)
      variant part: VariantPart
        name: SimpleName
          id --> sex
        variants ===
          [0]: Variant
            choices ===
              [0]: ExprChoice
                expr: NameExpr
                  name: SimpleName
                    id --> m
            components: ComponentList
              components ===
                [0]: ComponentDeclaration
                  names ===
                    [0] --> wife
                  type: SubtypeIndication
                    type_mark: SimpleName
                      id --> person_name
                    constraint: DiscriminantConstraint
                      list ===
                        [0]: DiscriminantAssociation
                          name ===
                            [0]: SimpleName
                              id --> sex
                          expr: NameExpr
                            name: SimpleName
                              id --> f
                  initializer: (null)
              variant part: (null)
          [1]: Variant
            choices ===
              [0]: ExprChoice
                expr: NameExpr
                  name: SimpleName
                    id --> f
            components: ComponentList
              components ===
                [0]: ComponentDeclaration
                  names ===
                    [0] --> husband
                  type: SubtypeIndication
                    type_mark: SimpleName
                      id --> person_name
                    constraint: DiscriminantConstraint
                      list ===
                        [0]: DiscriminantAssociation
                          name ===
                            [0]: SimpleName
                              id --> sex
                          expr: NameExpr
                            name: SimpleName
                              id --> m
                  initializer: (null)
              variant part: (null)
ObjectDeclaration
  names ===
    [0] --> my_car
    [1] --> your_car
    [2] --> next_car
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> car_name
    constraint: (null)
  initializer: (null)
TypeDecl
  name --> male
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> person
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name ===
            [0]: SimpleName
              id --> sex
          expr: NameExpr
            name: SimpleName
              id --> m


Listing for tst/declarations/tst00200.ada:
==========================================
     1   --
     2   -- -- This is a complete list of examples from Chapter 3
     3   --    --------------------------------------------------
     4
     5
     6   type BIT_VECTOR is array(INTEGER range <>) of BOOLEAN;
     7
     8   COUNT, SUM : INTEGER;
     9   SIZE : INTEGER range 0 .. 10_000 := 0;
    10   SORTED : BOOLEAN := FALSE;
    11
    12   N : constant := 3;
    13   K : constant := 100;
    14
    15   type COLOR is (WHITE, RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE, BROWN, BLACK);
    16
    17   COLOR_TABLE : array(1 .. N) of COLOR;
    18   --OPTION := BIT_VECTOR(1 .. 10) := (others => TRUE);
    19
    20   LIMIT : constant INTEGER := 10_000;
    21   LOW_LIMIT : constant INTEGER := LIMIT / 10;
    22   --TOLLERANNCE : constant REAL := DISPERSION(1.15);
    23
    24   PI : constant := 3.14159_26536;
    25   TWO_PI : constant := 2 * PI;
    26   MAX : constant := 500;
    27   POWER_16 : constant := 2 ** 16;
    28   ONE, UN, EINS : constant := 1;
    29
    30   type COLUMN is range 1 .. 72;
    31   type TABLE is array(1 .. 10) of INTEGER;
    32   type MATRIX is array(INTEGER range <>, INTEGER range <>) of REAL;
    33
    34   subtype RAINBOW is COLOR range RED .. PURPLE;
    35   subtype RED_PURPLE is RAINBOW;
    36   subtype INT is INTEGER;
    37   subtype SMALL_INT is INTEGER range -10 .. 10;
    38   subtype UP_TO_K is COLUMN range 1 .. K;
    39   subtype SQUARE_SUB is MATRIX(1 .. 10, 1 .. 10);
    40
    41   type COORDINATE is
    42       record
    43           LAT : REAL;
    44           LONG : REAL;
    45       end record;
    46
    47   type LOCAL_COORDINATE is new COORDINATE;
    48   type DAY is (MON, TUE, WED, THU, FRI, SAT, SUN);
    49   type MIDWEEK is new DAY range TUE .. THU;
    50   type POSITIVE is new INTEGER;
    51   type COUNTER is new POSITIVE;
    52   --type SPECIAL_KEY is new KEY_MANAGER.KEY;
    53
    54   type SUIT is (CLUBS, DIAMONDS, HEARTS, SPADES);
    55   type GENDER is (M, F);
    56   type LEVEL is (LOW, MEDIUM, URGENT);
    57   type LIGHT is (RED, AMBER, GREEN);
    58
    59   type HEXA is ('A', 'B', 'C', 'D', 'E', 'F');
    60   type MIXED is ('A', 'B', '*', NONE, '?', '%');
    61
    62   subtype WEEKDAY is DAY range MON .. FRI;
    63   subtype MAJOR is SUIT range HEARTS .. SPADES;
    64
    65   type ROMAN_DIGIT is ('I', 'V', 'X', 'L', 'C', 'D', 'M');
    66
    67   type PAGE_NUM is range 1 .. 2_000;
    68   MAX_LINE_SIZE : constant := 132;
    69   type LINE_SIZE is range 1 .. MAX_LINE_SIZE;
    70
    71   subtype COLUMN_PTR is LINE_SIZE range 1 .. 10;
    72   subtype BUFFER_SIZE is INTEGER range 0 .. MAX;
    73
    74   type COEFFICIENT is digits 4 range -1.0 .. 1.0;
    75   type MASS is digits 7 range 0.0 .. 1.0E35;
    76
    77   subtype SHORT_COEFF is COEFFICIENT digits 5;
    78   subtype PROBABILITY is REAL range 0.0 .. 1.0;
    79
    80   type VOLT is delta 0.125 range 0.0 .. 255.0;
    81
    82   subtype ROUGH_VOLTAGE is VOLT delta 1.0;
    83
    84   WORD_LENGTH : constant := 8;
    85
    86   DEL : constant := 1.0 / 2 ** (WORD_LENGTH - 1);
    87   type FRACTION is delta DEL range -1.0 .. 1.0 - DEL;
    88
    89   type VECTOR is array(INTEGER range <>) of REAL;
    90   type ROMAN is array(POSITIVE range <>) of ROMAN_DIGIT;
    91
    92   type SCHEDULE is array(DAY) of BOOLEAN;
    93   type LINE is array(1 .. MAX_LINE_SIZE) of CHARACTER;
    94
    95   GRID : array(1 .. 80, 1 .. 100) of BOOLEAN;
    96   MIX : array(COLOR range RED .. GREEN) of BOOLEAN;
    97   PAGE : array(1 .. 50) of LINE;
    98
    99   type MONTH_NAME is (JAN, FEB, MAR, APR, MAY, JUN,
   100           JUL, AUG, SEP, OCT, NOV, DEC);
   101
   102   type DATE is
   103       record
   104           DAY : INTEGER range 1 ..31;
   105           MONTH : MONTH_NAME;
   106           YEAR : INTEGER range 0 .. 4000;
   107       end record;
   108
   109
   110   type COMPLEX is
   111       record
   112           RE : REAL := 0.0;
   113           IM : REAL := 0.0;
   114       end record;
   115
   116   TOMORROW, YESTERDAY : DATE;
   117   A, B, C : COMPLEX;
   118
   119
   120   type BUFFER(SIZE : BUFFER_SIZE := 100) is
   121       record
   122           POS : BUFFER_SIZE := 0;
   123           VALUE : STRING(1 .. SIZE);
   124       end record;
   125
   126   type SQUARE(SIDE : INTEGER) is
   127       record
   128           MAT : MATRIX(1 .. SIDE, 1 .. SIDE);
   129       end record;
   130
   131   type DOUBLE_SQUARE(NUMBER : INTEGER) is
   132       record
   133           LEFT : SQUARE(NUMBER);
   134           RIGHT : SQUARE(NUMBER);
   135       end record;
   136
   137   type ITEM(NUMBER : POSITIVE) is
   138       record
   139           CONTENT : INTEGER;
   140           -- no component depends on the discriminant
   141       end record;
   142
   143
   144   type DEVICE is (PRINTER, DISK, DRUM);
   145   type STATE is (OPEN, CLOSED);
   146   type CYLINDER_INDEX is range 1 .. 50;
   147   type TRACK_NUMBER is range 1 .. 120;
   148
   149   PAGE_SIZE : constant := 55;
   150
   151   type PERIPHERAL(UNIT : DEVICE := DISK) is
   152       record
   153           STATUS : STATE;
   154           case UNIT is
   155               when PRINTER =>
   156                   LINE_COUNT : INTEGER range 1 .. PAGE_SIZE;
   157               when others =>
   158                   CYLINDER : CYLINDER_INDEX;
   159                   TRACK : TRACK_NUMBER;
   160           end case;
   161       end record;
   162
   163
   164   subtype DRUM_UNIT is PERIPHERAL(DRUM);
   165   subtype DISK_UNIT is PERIPHERAL(DISK);
   166
   167   WRITER : PERIPHERAL(UNIT => PRINTER);
   168   ARCHIVE : DISK_UNIT;
   169
   170
   171   type FRAME is access MATRIX;
   172   type BUFFER_NAME is access BUFFER;
   173
   174
   175   type CELL;
   176   type LINK is access CELL;
   177
   178   type CELL is
   179       record
   180           VALUE : INTEGER;
   181           SUCC : LINK;
   182           PRED : LINK;
   183       end record;
   184
   185   --HEAD : LINK := new CELL'(0, null, null);
   186   HEAD : LINK := new CELL;
   187   NEXT : LINK := HEAD.SUCC;
   188
   189
   190   type CAR;
   191
   192   type PERSON(SEX : GENDER);
   193
   194   type PERSON_NAME is access PERSON;
   195   type CAR_NAME is access CAR;
   196
   197   type CAR is
   198       record
   199           NUMBER : INTEGER;
   200           OWNER : PERSON_NAME;
   201       end record;
   202
   203   type PERSON(SEX : GENDER) is
   204       record
   205           NAME : STRING(1 .. 20);
   206           BIRTH : DATE;
   207           AGE : INTEGER range 1 .. 130;
   208           VEHICLE : CAR_NAME;
   209           case SEX is
   210               when M => WIFE : PERSON_NAME(SEX => F);
   211               when F => HUSBAND : PERSON_NAME(SEX => M);
   212           end case;
   213       end record;
   214
   215
   216   MY_CAR, YOUR_CAR, NEXT_CAR : CAR_NAME;
   217
   218
   219   subtype MALE is PERSON(SEX => M);
   220


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: bit_vector
Object Symbol: count
Object Symbol: sum
Object Symbol: size
Object Symbol: sorted
Object Symbol: n
Object Symbol: k
Type Symbol: color
EnumLiteral Symbol: white of type color
EnumLiteral Symbol: red of type color
EnumLiteral Symbol: orange of type color
EnumLiteral Symbol: yellow of type color
EnumLiteral Symbol: green of type color
EnumLiteral Symbol: blue of type color
EnumLiteral Symbol: purple of type color
EnumLiteral Symbol: brown of type color
EnumLiteral Symbol: black of type color
Object Symbol: color_table
Object Symbol: limit
Object Symbol: low_limit
Object Symbol: pi
Object Symbol: two_pi
Object Symbol: max
Object Symbol: power_16
Object Symbol: one
Object Symbol: un
Object Symbol: eins
Type Symbol: column
Type Symbol: table
Type Symbol: matrix
Type Symbol: rainbow
Type Symbol: red_purple
Type Symbol: int
Type Symbol: small_int
Type Symbol: up_to_k
Type Symbol: square_sub
Type Symbol: coordinate
Component Symbol: lat of type coordinate
Component Symbol: long of type coordinate
Type Symbol: local_coordinate
Type Symbol: day
EnumLiteral Symbol: mon of type day
EnumLiteral Symbol: tue of type day
EnumLiteral Symbol: wed of type day
EnumLiteral Symbol: thu of type day
EnumLiteral Symbol: fri of type day
EnumLiteral Symbol: sat of type day
EnumLiteral Symbol: sun of type day
Type Symbol: midweek
Type Symbol: positive
Type Symbol: counter
Type Symbol: suit
EnumLiteral Symbol: clubs of type suit
EnumLiteral Symbol: diamonds of type suit
EnumLiteral Symbol: hearts of type suit
EnumLiteral Symbol: spades of type suit
Type Symbol: gender
EnumLiteral Symbol: m of type gender
EnumLiteral Symbol: f of type gender
Type Symbol: level
EnumLiteral Symbol: low of type level
EnumLiteral Symbol: medium of type level
EnumLiteral Symbol: urgent of type level
Type Symbol: light
EnumLiteral Symbol: red of type light
EnumLiteral Symbol: amber of type light
EnumLiteral Symbol: green of type light
Type Symbol: hexa
EnumLiteral Symbol: 'A' of type hexa
EnumLiteral Symbol: 'B' of type hexa
EnumLiteral Symbol: 'C' of type hexa
EnumLiteral Symbol: 'D' of type hexa
EnumLiteral Symbol: 'E' of type hexa
EnumLiteral Symbol: 'F' of type hexa
Type Symbol: mixed
EnumLiteral Symbol: 'A' of type mixed
EnumLiteral Symbol: 'B' of type mixed
EnumLiteral Symbol: '*' of type mixed
EnumLiteral Symbol: none of type mixed
EnumLiteral Symbol: '?' of type mixed
EnumLiteral Symbol: '%' of type mixed
Type Symbol: weekday
Type Symbol: major
Type Symbol: roman_digit
EnumLiteral Symbol: 'I' of type roman_digit
EnumLiteral Symbol: 'V' of type roman_digit
EnumLiteral Symbol: 'X' of type roman_digit
EnumLiteral Symbol: 'L' of type roman_digit
EnumLiteral Symbol: 'C' of type roman_digit
EnumLiteral Symbol: 'D' of type roman_digit
EnumLiteral Symbol: 'M' of type roman_digit
Type Symbol: page_num
Object Symbol: max_line_size
Type Symbol: line_size
Type Symbol: column_ptr
Type Symbol: buffer_size
Type Symbol: coefficient
Type Symbol: mass
Type Symbol: short_coeff
Type Symbol: probability
Type Symbol: volt
Type Symbol: rough_voltage
Object Symbol: word_length
Object Symbol: del
Type Symbol: fraction
Type Symbol: vector
Type Symbol: roman
Type Symbol: schedule
Type Symbol: line
Object Symbol: grid
Object Symbol: mix
Object Symbol: page
Type Symbol: month_name
EnumLiteral Symbol: jan of type month_name
EnumLiteral Symbol: feb of type month_name
EnumLiteral Symbol: mar of type month_name
EnumLiteral Symbol: apr of type month_name
EnumLiteral Symbol: may of type month_name
EnumLiteral Symbol: jun of type month_name
EnumLiteral Symbol: jul of type month_name
EnumLiteral Symbol: aug of type month_name
EnumLiteral Symbol: sep of type month_name
EnumLiteral Symbol: oct of type month_name
EnumLiteral Symbol: nov of type month_name
EnumLiteral Symbol: dec of type month_name
Type Symbol: date
Component Symbol: day of type date
Component Symbol: month of type date
Component Symbol: year of type date
Type Symbol: complex
Component Symbol: re of type complex
Component Symbol: im of type complex
Object Symbol: tomorrow
Object Symbol: yesterday
Object Symbol: a
Object Symbol: b
Object Symbol: c
Discriminant Symbol: size of type buffer
Type Symbol: buffer
Component Symbol: pos of type buffer
Component Symbol: value of type buffer
Discriminant Symbol: side of type square
Type Symbol: square
Component Symbol: mat of type square
Discriminant Symbol: number of type double_square
Type Symbol: double_square
Component Symbol: left of type double_square
Component Symbol: right of type double_square
Discriminant Symbol: number of type item
Type Symbol: item
Component Symbol: content of type item
Type Symbol: device
EnumLiteral Symbol: printer of type device
EnumLiteral Symbol: disk of type device
EnumLiteral Symbol: drum of type device
Type Symbol: state
EnumLiteral Symbol: open of type state
EnumLiteral Symbol: closed of type state
Type Symbol: cylinder_index
Type Symbol: track_number
Object Symbol: page_size
Discriminant Symbol: unit of type peripheral
Type Symbol: peripheral
Component Symbol: status of type peripheral
Component Symbol: line_count of type peripheral
Component Symbol: cylinder of type peripheral
Component Symbol: track of type peripheral
Type Symbol: drum_unit
Type Symbol: disk_unit
Object Symbol: writer
Object Symbol: archive
Type Symbol: frame
Type Symbol: buffer_name
Type Symbol: cell
Type Symbol: link
Component Symbol: value of type cell
Component Symbol: succ of type cell
Component Symbol: pred of type cell
Object Symbol: head
Object Symbol: next
Type Symbol: car
Type Symbol: person
Discriminant Symbol: sex of type person
Type Symbol: person_name
Type Symbol: car_name
Component Symbol: number of type car
Component Symbol: owner of type car
Discriminant Symbol: sex of type person
Component Symbol: name of type person
Component Symbol: birth of type person
Component Symbol: age of type person
Component Symbol: vehicle of type person
Component Symbol: wife of type person
Component Symbol: husband of type person
Object Symbol: my_car
Object Symbol: your_car
Object Symbol: next_car
Type Symbol: male
-------------------

   Errors  : 0
   Warnings: 0
