PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> yellow
      [3] --> green
      [4] --> blue
      [5] --> brown
      [6] --> black
TypeDecl
  name --> rainbow
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> color
    constraint: RangeConstraint
      range: Range
        lower: NameExpr
          name: SimpleName
            id --> red
        upper: NameExpr
          name: SimpleName
            id --> blue


Listing for tst/declarations/tst00038.ada:
==========================================
     1   type COLOR is (WHITE, RED, YELLOW, GREEN, BLUE, BROWN, BLACK);
     2
     3   subtype RAINBOW is COLOR range RED .. BLUE;
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Enumeration Type: color : Enumeration
   containing literals (white red yellow green blue brown black )
Enumeration Literal: white : EnumLiteral of type color; value (0)
Enumeration Literal: red : EnumLiteral of type color; value (1)
Enumeration Literal: yellow : EnumLiteral of type color; value (2)
Enumeration Literal: green : EnumLiteral of type color; value (3)
Enumeration Literal: blue : EnumLiteral of type color; value (4)
Enumeration Literal: brown : EnumLiteral of type color; value (5)
Enumeration Literal: black : EnumLiteral of type color; value (6)
Subtype: rainbow : Subtype
-------------------

   Errors  : 0
   Warnings: 0
