PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> yellow
      [3] --> green
      [4] --> blue
      [5] --> brown
      [6] --> black
ObjectDeclaration
  names ===
    [0] --> mix
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: SubtypeRange
          subtype: SubtypeIndication
            type_mark: SimpleName
              id --> color
            constraint: RangeConstraint
              range: Range
                lower: NameExpr
                  name: SimpleName
                    id --> red
                upper: NameExpr
                  name: SimpleName
                    id --> green
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
  initializer: (null)


Listing for tst/declarations/tst00062.ada:
==========================================
     1   type COLOR is (WHITE, RED, YELLOW, GREEN, BLUE, BROWN, BLACK);
     2   MIX : array(COLOR range RED .. GREEN) of BOOLEAN;
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: color
EnumLiteral Symbol: white of type color
EnumLiteral Symbol: red of type color
EnumLiteral Symbol: yellow of type color
EnumLiteral Symbol: green of type color
EnumLiteral Symbol: blue of type color
EnumLiteral Symbol: brown of type color
EnumLiteral Symbol: black of type color
Object Symbol: mix
-------------------

   Errors  : 0
   Warnings: 0
