PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> matrix
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
        [1]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> real
      constraint: (null)
TypeDecl
  name --> square
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> side
      type: SimpleName
        id --> integer
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> mat
          type: SubtypeIndication
            type_mark: SimpleName
              id --> matrix
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> side
                [1]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> side
          initializer: (null)
      variant part: (null)
ObjectDeclaration
  names ===
    [0] --> basis
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> square
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name === (null/empty)
          expr: IntLiteralExpr
            value --> 5
  initializer: (null)


Listing for tst/declarations/tst00084.ada:
==========================================
     1   type MATRIX is array(INTEGER range <>, INTEGER range <>) of REAL;
     2
     3   type SQUARE(SIDE : INTEGER) is
     4       record
     5           MAT : MATRIX(1 .. SIDE, 1 .. SIDE);
     6       end record;
     7
     8   BASIS : SQUARE(5);
     9


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: matrix
Discriminant Symbol: side of type square
Type Symbol: square
Component Symbol: mat of type square
Object Symbol: basis
-------------------

   Errors  : 0
   Warnings: 0
