PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> matrix
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
        [1]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> real
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> board
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> matrix
    constraint: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 8
        [1]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 8
  initializer: (null)


Listing for tst/declarations/tst00064.ada:
==========================================
     1   type MATRIX is array(INTEGER range <>, INTEGER range <>) of REAL;
     2   BOARD : MATRIX( 1 .. 8, 1 .. 8);
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: matrix
Object Symbol: board
-------------------

   Errors  : 0
   Warnings: 0
