PRINTING THE AST STRUCTURE
==========================
ObjectDeclaration
  names ===
    [0] --> max
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 65535
TypeDecl
  name --> buffer_size
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 0
        upper: NameExpr
          name: SimpleName
            id --> max
TypeDecl
  name --> buffer
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> size
      type: SimpleName
        id --> buffer_size
      expr: IntLiteralExpr
        value --> 100
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> pos
          type: SubtypeIndication
            type_mark: SimpleName
              id --> buffer_size
            constraint: (null)
          initializer: IntLiteralExpr
            value --> 0
        [1]: ComponentDeclaration
          names ===
            [0] --> value
          type: SubtypeIndication
            type_mark: SimpleName
              id --> string
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> size
          initializer: (null)
      variant part: (null)


Listing for tst/declarations/tst00078.ada:
==========================================
     1   MAX : constant := 65535;
     2   subtype BUFFER_SIZE is INTEGER range 0 .. MAX;
     3   type BUFFER(SIZE : BUFFER_SIZE := 100) is
     4       record
     5           POS : BUFFER_SIZE := 0;
     6           VALUE : STRING(1 .. SIZE);
     7       end record;
     8


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: max : Object
Type Symbol: buffer_size : Type
Discriminant Symbol: size : Discriminant of type buffer_size
Type Symbol: buffer : Type
Component Symbol: pos : Component of type buffer
Component Symbol: value : Component of type buffer
-------------------

   Errors  : 0
   Warnings: 0
