TypeDecl
  name --> day
  discriminantPart === (null)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> mon
      [1] --> tue
      [2] --> wed
      [3] --> thu
      [4] --> fri
      [5] --> sat
      [6] --> sun


Listing for tst/declarations/tst00028.ada:
==========================================
     1   type DAY is (MON, TUE, WED, THU, FRI, SAT, SUN);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Enumeration Type: day : Enumeration
   containing literals (mon tue wed thu fri sat sun )
Enumeration Literal: mon : EnumLiteral of type day; value (0)
Enumeration Literal: tue : EnumLiteral of type day; value (1)
Enumeration Literal: wed : EnumLiteral of type day; value (2)
Enumeration Literal: thu : EnumLiteral of type day; value (3)
Enumeration Literal: fri : EnumLiteral of type day; value (4)
Enumeration Literal: sat : EnumLiteral of type day; value (5)
Enumeration Literal: sun : EnumLiteral of type day; value (6)
-------------------
