PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> yellow
      [3] --> green
      [4] --> blue
      [5] --> brown
      [6] --> black
TypeDecl
  name --> cmyk
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> cyan
      [1] --> magenta
      [2] --> yellow
      [3] --> black


Listing for tst/declarations/tst00104.ada:
==========================================
     1   type COLOR is (WHITE, RED, YELLOW, GREEN, BLUE, BROWN, BLACK);
     2   type CMYK is (CYAN, MAGENTA, YELLOW, BLACK);
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: color
EnumLiteral Symbol: white of type color
EnumLiteral Symbol: red of type color
EnumLiteral Symbol: yellow of type color
EnumLiteral Symbol: green of type color
EnumLiteral Symbol: blue of type color
EnumLiteral Symbol: brown of type color
EnumLiteral Symbol: black of type color
Type Symbol: cmyk
EnumLiteral Symbol: cyan of type cmyk
EnumLiteral Symbol: magenta of type cmyk
EnumLiteral Symbol: yellow of type cmyk
EnumLiteral Symbol: black of type cmyk
-------------------

   Errors  : 0
   Warnings: 0
