PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> yellow
      [3] --> green
      [4] --> blue
      [5] --> brown
      [6] --> black


Listing for tst/declarations/tst00014.ada:
==========================================
     1   type COLOR is (WHITE, RED, YELLOW, GREEN, BLUE, BROWN, BLACK);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: color : Type
EnumLiteral Symbol: white : EnumLiteral of type color
EnumLiteral Symbol: red : EnumLiteral of type color
EnumLiteral Symbol: yellow : EnumLiteral of type color
EnumLiteral Symbol: green : EnumLiteral of type color
EnumLiteral Symbol: blue : EnumLiteral of type color
EnumLiteral Symbol: brown : EnumLiteral of type color
EnumLiteral Symbol: black : EnumLiteral of type color
-------------------

   Errors  : 0
   Warnings: 0
