TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: (null)
TypeDecl
  name --> male
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> person
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name ===
            [0]: SimpleName
              id --> sex
          expr: NameExpr
            name: SimpleName
              id --> m


Listing for tst/declarations/tst00023.ada:
==========================================
     1   type GENDER is (M, F);
     2   type PERSON(SEX : GENDER);
     3   subtype MALE is PERSON(SEX => M);
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Enumeration Type: gender : Enumeration
   containing literals (m f )
Enumeration Literal: m : EnumLiteral of type gender; value (0)
Enumeration Literal: f : EnumLiteral of type gender; value (1)
Incomplete Type: person : Incomplete
Discriminant Symbol: sex : Discriminant
Subtype: male : Subtype
-------------------
