TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: (null)
TypeDecl
  name --> person_name
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> person
      constraint: (null)
TypeDecl
  name --> car
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> number
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: (null)
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> owner
          type: SubtypeIndication
            type_mark: SimpleName
              id --> person_name
            constraint: (null)
          initializer: (null)
      variant part: (null)


Listing for tst/declarations/tst00101.ada:
==========================================
     1   type GENDER is (M, F);
     2
     3   type PERSON(SEX : GENDER);
     4
     5   type PERSON_NAME is access PERSON;
     6
     7   type CAR is
     8       record
     9           NUMBER : INTEGER;
    10           OWNER : PERSON_NAME;
    11       end record;
    12


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Enumeration Type: gender : Enumeration
   containing literals (m f )
Enumeration Literal: m : EnumLiteral of type gender; value (0)
Enumeration Literal: f : EnumLiteral of type gender; value (1)
Incomplete Type: person : Incomplete
Discriminant Symbol: sex : Discriminant
Access Type: person_name : Access
Record Type: car : Record
   containing components (number owner )
-------------------

Scope Name: car
Scope ID  : 2
-------------------
Component Symbol: number : Component
Component Symbol: owner : Component
-------------------
