PRINTING THE AST STRUCTURE
==========================
ObjectDeclaration
  names ===
    [0] --> grid
  constant --> false
  typeSpec: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 80
        [1]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 100
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
  initializer: (null)


Listing for tst/declarations/tst00061.ada:
==========================================
     1   GRID : array(1 .. 80, 1 .. 100) of BOOLEAN;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: grid : Object
-------------------

   Errors  : 0
   Warnings: 0
