PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> color
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> white
      [1] --> red
      [2] --> yellow
      [3] --> green
      [4] --> blue
      [5] --> brown
      [6] --> black
TypeDecl
  name --> rainbow
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> color
    constraint: RangeConstraint
      range: Range
        lower: NameExpr
          name: SimpleName
            id --> red
        upper: NameExpr
          name: SimpleName
            id --> blue


Listing for tst/declarations/tst00017.ada:
==========================================
     1   type COLOR is (WHITE, RED, YELLOW, GREEN, BLUE, BROWN, BLACK);
     2
     3   subtype RAINBOW is COLOR range RED .. BLUE;
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: color
EnumLiteral Symbol: white of type color
EnumLiteral Symbol: red of type color
EnumLiteral Symbol: yellow of type color
EnumLiteral Symbol: green of type color
EnumLiteral Symbol: blue of type color
EnumLiteral Symbol: brown of type color
EnumLiteral Symbol: black of type color
Type Symbol: rainbow
-------------------

   Errors  : 0
   Warnings: 0
