PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> bit_vector
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> option
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> bit_vector
    constraint: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 10
  initializer: AggregateExpr
    list ===
      [0]: ComponentAssociation
        choices ===
          [0]: OthersChoice
            others --> Others
        expr: NameExpr
          name: SimpleName
            id --> true


Listing for tst/declarations/tst00005.ada:
==========================================
     1   type BIT_VECTOR is array(INTEGER range <>) of BOOLEAN;
     2   OPTION      : BIT_VECTOR(1 .. 10) := (others => TRUE);
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: bit_vector
Object Symbol: option
-------------------

   Errors  : 0
   Warnings: 0
