PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> coefficient
  discriminantPart === (null/empty)
  definition: NumericTypeSpec
    kind --> Floating Point
    digits: IntLiteralExpr
      value --> 10
    range: RangeConstraint
      range: Range
        lower: UnaryExpr
          op --> - (minus)
          operand: RealLiteralExpr
            value --> 1.0
        upper: RealLiteralExpr
          value --> 1.0


Listing for tst/declarations/tst00045.ada:
==========================================
     1   type COEFFICIENT is digits 10 range -1.0 .. 1.0;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: coefficient
-------------------

   Errors  : 0
   Warnings: 0
