PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> month_name
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> jan
      [1] --> feb
      [2] --> mar
      [3] --> apr
      [4] --> may
      [5] --> jun
      [6] --> jul
      [7] --> aug
      [8] --> sep
      [9] --> oct
      [10] --> nov
      [11] --> dec
TypeDecl
  name --> date
  discriminantPart === (null/empty)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> day
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 1
                upper: IntLiteralExpr
                  value --> 31
          initializer: (null)
        [1]: ComponentDeclaration
          names ===
            [0] --> month
          type: SubtypeIndication
            type_mark: SimpleName
              id --> month_name
            constraint: (null)
          initializer: (null)
        [2]: ComponentDeclaration
          names ===
            [0] --> year
          type: SubtypeIndication
            type_mark: SimpleName
              id --> integer
            constraint: RangeConstraint
              range: Range
                lower: IntLiteralExpr
                  value --> 0
                upper: IntLiteralExpr
                  value --> 4000
          initializer: (null)
      variant part: (null)
ObjectDeclaration
  names ===
    [0] --> tomorrow
    [1] --> yesterday
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> date
    constraint: (null)
  initializer: (null)


Listing for tst/declarations/tst00076.ada:
==========================================
     1   type MONTH_NAME is (JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC);
     2   type DATE is
     3       record
     4           DAY : INTEGER range 1 .. 31;
     5           MONTH : MONTH_NAME;
     6           YEAR : INTEGER range 0 .. 4000;
     7       end record;
     8   TOMORROW, YESTERDAY : DATE;
     9


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: month_name : Type
EnumLiteral Symbol: jan : EnumLiteral of type month_name
EnumLiteral Symbol: feb : EnumLiteral of type month_name
EnumLiteral Symbol: mar : EnumLiteral of type month_name
EnumLiteral Symbol: apr : EnumLiteral of type month_name
EnumLiteral Symbol: may : EnumLiteral of type month_name
EnumLiteral Symbol: jun : EnumLiteral of type month_name
EnumLiteral Symbol: jul : EnumLiteral of type month_name
EnumLiteral Symbol: aug : EnumLiteral of type month_name
EnumLiteral Symbol: sep : EnumLiteral of type month_name
EnumLiteral Symbol: oct : EnumLiteral of type month_name
EnumLiteral Symbol: nov : EnumLiteral of type month_name
EnumLiteral Symbol: dec : EnumLiteral of type month_name
Type Symbol: date : Type
Component Symbol: day : Component of type date
Component Symbol: month : Component of type date
Component Symbol: year : Component of type date
Object Symbol: tomorrow : Object
Object Symbol: yesterday : Object
-------------------

   Errors  : 0
   Warnings: 0
