PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: (null)


Listing for tst/declarations/tst00097.ada:
==========================================
     1   type GENDER is (M, F);
     2
     3   type PERSON(SEX : GENDER);
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: gender
EnumLiteral Symbol: m of type gender
EnumLiteral Symbol: f of type gender
IncompleteType Symbol: person
Discriminant Symbol: sex of type gender
-------------------

   Errors  : 0
   Warnings: 0
