PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> roman_digit
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'I'
      [1] --> 'V'
      [2] --> 'X'
      [3] --> 'L'
      [4] --> 'C'
      [5] --> 'D'
      [6] --> 'M'


Listing for tst/declarations/tst00039.ada:
==========================================
     1   type ROMAN_DIGIT is ('I', 'V', 'X', 'L', 'C', 'D', 'M');
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Enumeration Type: roman_digit : Enumeration
   containing literals ('I' 'V' 'X' 'L' 'C' 'D' 'M' )
Enumeration Literal: 'I' : EnumLiteral of type roman_digit; value (0)
Enumeration Literal: 'V' : EnumLiteral of type roman_digit; value (1)
Enumeration Literal: 'X' : EnumLiteral of type roman_digit; value (2)
Enumeration Literal: 'L' : EnumLiteral of type roman_digit; value (3)
Enumeration Literal: 'C' : EnumLiteral of type roman_digit; value (4)
Enumeration Literal: 'D' : EnumLiteral of type roman_digit; value (5)
Enumeration Literal: 'M' : EnumLiteral of type roman_digit; value (6)
-------------------

   Errors  : 0
   Warnings: 0
