PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> var_line
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> length
      type: SimpleName
        id --> integer
      expr: (null)
  definition: RecordSpecification
    components: ComponentList
      components ===
        [0]: ComponentDeclaration
          names ===
            [0] --> image
          type: SubtypeIndication
            type_mark: SimpleName
              id --> string
            constraint: IndexConstraint
              unconstrained --> false
              indices ===
                [0]: Range
                  lower: IntLiteralExpr
                    value --> 1
                  upper: NameExpr
                    name: SimpleName
                      id --> length
          initializer: (null)
      variant part: (null)
ObjectDeclaration
  names ===
    [0] --> null_line
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> var_line
    constraint: DiscriminantConstraint
      list ===
        [0]: DiscriminantAssociation
          name === (null/empty)
          expr: IntLiteralExpr
            value --> 0
  initializer: (null)


Listing for tst/declarations/tst00069.ada:
==========================================
     1   type VAR_LINE(LENGTH : INTEGER) is
     2       record
     3           IMAGE : STRING(1 .. LENGTH);
     4       end record;
     5
     6   NULL_LINE : VAR_LINE(0);
     7


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Discriminant Symbol: length : Discriminant of type integer
Type Symbol: var_line : Type
Component Symbol: image : Component of type var_line
Object Symbol: null_line : Object
-------------------

   Errors  : 0
   Warnings: 0
