PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> day
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> mon
      [1] --> tue
      [2] --> wed
      [3] --> thu
      [4] --> fri
      [5] --> sat
      [6] --> sun
TypeDecl
  name --> midweek
  discriminantPart === (null/empty)
  definition: DerivedTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> day
      constraint: RangeConstraint
        range: Range
          lower: NameExpr
            name: SimpleName
              id --> tue
          upper: NameExpr
            name: SimpleName
              id --> thu


Listing for tst/declarations/tst00025.ada:
==========================================
     1   type DAY is (MON, TUE, WED, THU, FRI, SAT, SUN);
     2   type MIDWEEK is new DAY range TUE .. THU;
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: day
EnumLiteral Symbol: mon of type day
EnumLiteral Symbol: tue of type day
EnumLiteral Symbol: wed of type day
EnumLiteral Symbol: thu of type day
EnumLiteral Symbol: fri of type day
EnumLiteral Symbol: sat of type day
EnumLiteral Symbol: sun of type day
Type Symbol: midweek
-------------------

   Errors  : 0
   Warnings: 0
