TypeDecl
  name --> bit_vector
  discriminantPart === (null)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)


Listing for tst/declarations/tst00056.ada:
==========================================
     1   type BIT_VECTOR is array(INTEGER range <>) of BOOLEAN;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Array Type: bit_vector : Array
-------------------
