PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> int
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: (null)


Listing for tst/declarations/tst00019.ada:
==========================================
     1   subtype INT is INTEGER;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: int
-------------------

   Errors  : 0
   Warnings: 0
