PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> day
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> mon
      [1] --> tue
      [2] --> wed
      [3] --> thu
      [4] --> fri
      [5] --> sat
      [6] --> sun
TypeDecl
  name --> weekday
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> day
    constraint: RangeConstraint
      range: Range
        lower: NameExpr
          name: SimpleName
            id --> mon
        upper: NameExpr
          name: SimpleName
            id --> fri


Listing for tst/declarations/tst00036.ada:
==========================================
     1   type DAY is (MON, TUE, WED, THU, FRI, SAT, SUN);
     2   subtype WEEKDAY is DAY range MON .. FRI;
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: day
EnumLiteral Symbol: mon of type day
EnumLiteral Symbol: tue of type day
EnumLiteral Symbol: wed of type day
EnumLiteral Symbol: thu of type day
EnumLiteral Symbol: fri of type day
EnumLiteral Symbol: sat of type day
EnumLiteral Symbol: sun of type day
Type Symbol: weekday
-------------------

   Errors  : 0
   Warnings: 0
