PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> mixed
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'A'
      [1] --> 'B'
      [2] --> '*'
      [3] --> b
      [4] --> none
      [5] --> '?'
      [6] --> '%'


Listing for tst/declarations/tst00035.ada:
==========================================
     1   type MIXED is ('A', 'B', '*', B, NONE, '?', '%');
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: mixed
EnumLiteral Symbol: 'A' of type mixed
EnumLiteral Symbol: 'B' of type mixed
EnumLiteral Symbol: '*' of type mixed
EnumLiteral Symbol: b of type mixed
EnumLiteral Symbol: none of type mixed
EnumLiteral Symbol: '?' of type mixed
EnumLiteral Symbol: '%' of type mixed
-------------------

   Errors  : 0
   Warnings: 0
