PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> table
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 10
    component: SubtypeIndication
      type_mark: SimpleName
        id --> integer
      constraint: (null)


Listing for tst/declarations/tst00016.ada:
==========================================
     1   type TABLE is array(1 .. 10) of INTEGER;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Array Type: table : Array
-------------------

   Errors  : 0
   Warnings: 0
