PRINTING THE AST STRUCTURE
==========================
ObjectDeclaration
  names ===
    [0] --> max_line_size
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 132
TypeDecl
  name --> line
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: NameExpr
            name: SimpleName
              id --> max_line_size
    component: SubtypeIndication
      type_mark: SimpleName
        id --> character
      constraint: (null)


Listing for tst/declarations/tst00060.ada:
==========================================
     1   MAX_LINE_SIZE : constant := 132;
     2   type LINE is array(1 .. MAX_LINE_SIZE) of CHARACTER;
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: max_line_size : Object
Type Symbol: line : Type
-------------------

   Errors  : 0
   Warnings: 0
