PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> suit
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> clubs
      [1] --> diamonds
      [2] --> hearts
      [3] --> spades


Listing for tst/declarations/tst00029.ada:
==========================================
     1   type suit is (CLUBS, DIAMONDS, HEARTS, SPADES);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: suit : Type
EnumLiteral Symbol: clubs : EnumLiteral of type suit
EnumLiteral Symbol: diamonds : EnumLiteral of type suit
EnumLiteral Symbol: hearts : EnumLiteral of type suit
EnumLiteral Symbol: spades : EnumLiteral of type suit
-------------------

   Errors  : 0
   Warnings: 0
