PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> car
  discriminantPart === (null/empty)
  definition: (null)


Listing for tst/declarations/tst00098.ada:
==========================================
     1   type CAR;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
IncompleteType Symbol: car : IncompleteType
-------------------

   Errors  : 0
   Warnings: 0
