PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f
TypeDecl
  name --> person
  discriminantPart ===
    [0]: DiscriminantSpecification
      ids ===
        [0] --> sex
      type: SimpleName
        id --> gender
      expr: (null)
  definition: (null)
TypeDecl
  name --> person_name
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> person
      constraint: (null)


Listing for tst/declarations/tst00099.ada:
==========================================
     1   type GENDER is (M, F);
     2
     3   type PERSON(SEX : GENDER);
     4
     5   type PERSON_NAME is access PERSON;
     6


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: gender : Type
EnumLiteral Symbol: m : EnumLiteral of type gender
EnumLiteral Symbol: f : EnumLiteral of type gender
IncompleteType Symbol: person : IncompleteType
Discriminant Symbol: sex : Discriminant of type gender
Type Symbol: person_name : Type
-------------------

   Errors  : 0
   Warnings: 0
