PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> bit_vector
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> boolean
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> filter
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> bit_vector
    constraint: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 0
          upper: IntLiteralExpr
            value --> 31
  initializer: (null)


Listing for tst/declarations/tst00067.ada:
==========================================
     1   type BIT_VECTOR is array(INTEGER range <>) of BOOLEAN;
     2   FILTER : BIT_VECTOR(0 .. 31);
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: bit_vector : Type
Object Symbol: filter : Object
-------------------

   Errors  : 0
   Warnings: 0
