ObjectDeclaration
  names ===
    [0] --> n
  constant --> true
  typeSpec: (null)
  initializer: IntLiteralExpr
    value --> 8
TypeDecl
  name --> matrix
  discriminantPart === (null)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> integer
        [1]: UnboundedRange
          type: SimpleName
            id --> integer
    component: SubtypeIndication
      type_mark: SimpleName
        id --> real
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> inverse
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> matrix
    constraint: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: NameExpr
            name: SimpleName
              id --> n
        [1]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: NameExpr
            name: SimpleName
              id --> n
  initializer: (null)


Listing for tst/declarations/tst00066.ada:
==========================================
     1   N : constant := 8;
     2   type MATRIX is array(INTEGER range <>, INTEGER range <>) of REAL;
     3   INVERSE : MATRIX(1 .. N, 1 .. N);
     4


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: n : Object
Array Type: matrix : Array
Object Symbol: inverse : Object
-------------------
