PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> light
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> red
      [1] --> amber
      [2] --> green


Listing for tst/declarations/tst00033.ada:
==========================================
     1   type LIGHT is (RED, AMBER, GREEN);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: light
EnumLiteral Symbol: red of type light
EnumLiteral Symbol: amber of type light
EnumLiteral Symbol: green of type light
-------------------

   Errors  : 0
   Warnings: 0
