PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> state
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> open
      [1] --> closed


Listing for tst/declarations/tst00086.ada:
==========================================
     1   type STATE is (OPEN, CLOSED);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: state : Type
EnumLiteral Symbol: open : EnumLiteral of type state
EnumLiteral Symbol: closed : EnumLiteral of type state
-------------------

   Errors  : 0
   Warnings: 0
