PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> gender
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> m
      [1] --> f


Listing for tst/declarations/tst00030.ada:
==========================================
     1   type GENDER is (M, F);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: gender
EnumLiteral Symbol: m of type gender
EnumLiteral Symbol: f of type gender
-------------------

   Errors  : 0
   Warnings: 0
