ObjectDeclaration
  names ===
    [0] --> sorted
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> boolean
    constraint: (null)
  initializer: NameExpr
    name: SimpleName
      id --> false


Listing for tst/declarations/tst00003.ada:
==========================================
     1   SORTED      : BOOLEAN := FALSE;
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: sorted : Object
-------------------
