PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> positive
  discriminantPart === (null/empty)
  definition: SubtypeIndication
    type_mark: SimpleName
      id --> integer
    constraint: RangeConstraint
      range: Range
        lower: IntLiteralExpr
          value --> 1
        upper: NameExpr
          name: AttributeName
            prefix: SimpleName
              id --> integer
            attribute: SimpleName
              id --> last
            expr: (null)
TypeDecl
  name --> roman_digit
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> 'I'
      [1] --> 'V'
      [2] --> 'X'
      [3] --> 'L'
      [4] --> 'C'
      [5] --> 'D'
      [6] --> 'M'
TypeDecl
  name --> roman
  discriminantPart === (null/empty)
  definition: ArrayTypeSpec
    indices: IndexConstraint
      unconstrained --> true
      indices ===
        [0]: UnboundedRange
          type: SimpleName
            id --> positive
    component: SubtypeIndication
      type_mark: SimpleName
        id --> roman_digit
      constraint: (null)
ObjectDeclaration
  names ===
    [0] --> ninety_six
  constant --> true
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> roman
    constraint: (null)
  initializer: StringLiteralExpr
    value --> XCVI


Listing for tst/declarations/tst00073.ada:
==========================================
     1   subtype POSITIVE is INTEGER range 1 .. INTEGER'LAST;
     2   type ROMAN_DIGIT is ('I', 'V', 'X', 'L', 'C', 'D', 'M');
     3   type ROMAN is array(POSITIVE range <>) of ROMAN_DIGIT;
     4   NINETY_SIX : constant ROMAN := "XCVI";
     5


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: positive : Type
Type Symbol: roman_digit : Type
EnumLiteral Symbol: 'I' : EnumLiteral of type roman_digit
EnumLiteral Symbol: 'V' : EnumLiteral of type roman_digit
EnumLiteral Symbol: 'X' : EnumLiteral of type roman_digit
EnumLiteral Symbol: 'L' : EnumLiteral of type roman_digit
EnumLiteral Symbol: 'C' : EnumLiteral of type roman_digit
EnumLiteral Symbol: 'D' : EnumLiteral of type roman_digit
EnumLiteral Symbol: 'M' : EnumLiteral of type roman_digit
Type Symbol: roman : Type
Object Symbol: ninety_six : Object
-------------------

   Errors  : 0
   Warnings: 0
