PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> device
  discriminantPart === (null/empty)
  definition: EnumerationTypeSpec
    literals ===
      [0] --> printer
      [1] --> disk
      [2] --> drum


Listing for tst/declarations/tst00085.ada:
==========================================
     1   type DEVICE is (PRINTER, DISK, DRUM);
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Type Symbol: device : Type
EnumLiteral Symbol: printer : EnumLiteral of type device
EnumLiteral Symbol: disk : EnumLiteral of type device
EnumLiteral Symbol: drum : EnumLiteral of type device
-------------------

   Errors  : 0
   Warnings: 0
