PRINTING THE AST STRUCTURE
==========================
TypeDecl
  name --> cell
  discriminantPart === (null/empty)
  definition: (null)
TypeDecl
  name --> link
  discriminantPart === (null/empty)
  definition: AccessTypeSpec
    type: SubtypeIndication
      type_mark: SimpleName
        id --> cell
      constraint: (null)


Listing for tst/declarations/tst00093.ada:
==========================================
     1   type CELL;
     2   type LINK is access CELL;
     3


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
IncompleteType Symbol: cell : IncompleteType
Type Symbol: link : Type
-------------------

   Errors  : 0
   Warnings: 0
