PRINTING THE AST STRUCTURE
==========================
ObjectDeclaration
  names ===
    [0] --> stars
  constant --> false
  typeSpec: SubtypeIndication
    type_mark: SimpleName
      id --> string
    constraint: IndexConstraint
      unconstrained --> false
      indices ===
        [0]: Range
          lower: IntLiteralExpr
            value --> 1
          upper: IntLiteralExpr
            value --> 120
  initializer: AggregateExpr
    list ===
      [0]: ComponentAssociation
        choices ===
          [0]: RangeChoice
            range: Range
              lower: IntLiteralExpr
                value --> 1
              upper: IntLiteralExpr
                value --> 120
        expr: NameExpr
          name: CharacterLiteralName
            literal --> '*'


Listing for tst/declarations/tst00070.ada:
==========================================
     1   STARS : STRING(1 .. 120) := (1 .. 120 => '*');
     2


=========================================
=========================================
====   Printing Symbol Scope Stack   ====
=========================================
=========================================

Scope Name: GLOBAL
Scope ID  : 1
-------------------
Object Symbol: stars
-------------------

   Errors  : 0
   Warnings: 0
