type MONTH_NAME is (JANUARY, FEBRUARY, MARCH, APRIL, MAY, JUNE, JULY,
        AUGUST, SEPTEMBER, OCTOBER, NOVEMBER, DECEMBER);
MONTH : MONTH_NAME;
DAY : INTEGER range 1 .. 31;
YEAR : INTEGER;

MONTH := DECEMBER;
DAY := 31;
YEAR := 2026;

if MONTH = DECEMBER and DAY = 31 then
    MONTH := JANUARY;
    DAY := 1;
    YEAR := YEAR + 1;
end if;

